### ISSUE TITLE
Using only the license checker

### ISSUE THREAD

**Issue by akirak** [riscy/melpazoid#11]
Is it possible to run `melpazoid.py` (or its licence checker) without Docker? 

I'm trying to integrate melpazoid into Nix, and I've successfully run extra checks provided by `melpazoid.el` in Nix: https://github.com/akirak/melpa-check/pull/24 (Note: I plan on rewriting the project from scratch for much less code, so the PR is just a demonstration.)

I'm also trying to run `melpazoid.py` (for the license checker) in Nix, but it invokes `make test`, which in turn starts building a Docker container, which causes the same issue as #1. 

Since Docker is often used for similar purposes to Nix, it would be better if `melpazoid.py` could be run without Docker, or allow running only the license checker. There are many CI solutions for elisp projects out there, but AFAIK none of them check license, so it would be convenient to allow using the license checker independently.

**Comment by riscy** [comment]
Neat, I'm excited to see those checks in Nix.  They're sort of a hack (no syntax tree) but they seem to be useful.

Given what you write above, maybe it's time to split the license checker out into its own module that can be accessed through some CLI.  Something like this?

```bash
python3 check_license.py </path/to/elisp/*.el> [--github-repo=optional]
```

**Comment by akirak** [comment]
> maybe it's time to split the license checker out into its own module that can be accessed through some CLI. 

Thanks, that's a good idea. Melpazoid looks like a complete suite for checking packages, but I don't have Docker on every machine, so I like to implement an alternative in Nix. Recently, Nix has got an elisp parser (written purely in the language), which makes it really a nice tool for Emacs developers. [emacs-overlay](https://github.com/nix-community/emacs-overlay/) is a hub for Nix + Emacs people.

Regarding use of the experimental checker from outside, I basically set `noninteracrive` to nil to disable other checks and and printed the contents of melpazoid-buffer to stdout. I transformed the output, but it's just a preference and not necessary. It's indeed a hack, but it was not hard at all.

**Comment by riscy** [comment]
This has been slow coming as I've been thinking about factoring stuff out, but I decided it'd be best to keep the file intact for now.  I'm thinking of something like:

```bash
python3 melpazoid.py --license [target]
```

For your use case, were you thinking [target] would tend to be on the local file system, or a repository somewhere?

**Comment by akirak** [comment]
@riscy Thanks, I'm going to run it in a local working tree. It has a feature to clone remote repositories, but it's basically run locally: Repositories are first cloned using Nix to a read-only file system, and then copied to (actually symlinked) writable sandboxes. Only files specified in recipes are copied to sandboxes, so I'll probably run the license checker in the read-only Nix store before copying. It would be better if the license checker didn't involve any write operation, but there will be a workaround anyways.

Since I use [niv](https://github.com/nmattia/niv) to freeze dependencies in my Nix projects, your changes won't affect my project until I update the dependency. Please feel free to reorganise your project to your liking.

**Comment by riscy** [comment]
This is [on master now](https://github.com/riscy/melpazoid#only-test-a-packages-licenses).

**Comment by akirak** [comment]
Thank you for this work. It detected a license in my project, and its API is good to me. I also noticed some changes in the experimental checks, so I will update my project soon.
