### ISSUE TITLE
Mention compilation features in docs

### ISSUE THREAD

**Issue by progfolio** [riscy/melpazoid#12]
Thanks for the scripts.
Today I was using melpazoid on a package I'm developing and was surprised to see:

byte-compile (using Emacs 27.1):
```
wikinfo.el:254:1:Warning: the following functions are not known to be defined:
    json-parse-string, libxml-parse-html-region
```

I assume the docker image is not compiled w JSON or libxml support.
Editing the file is easy enough, but it might be worth it to mention this in the docs and/or introduce another environmental variable to add compile options for the container's Emacs build.

**Comment by riscy** [comment]
This is a good catch - the ubuntu base layer is quite bare so a couple of dependencies would also have to be installed.  I took a look and it would add around 100MB to the image which isn't terrible, and I might be able to cut that back.  Definitely worth mentioning in the docs, and maybe even supporting by default now that I think about it.  Thanks -- stay tuned.
