### ISSUE TITLE
Setting LOCAL_REPO in the GitHub Actions workflow

### ISSUE THREAD

**Issue by akirak** [riscy/melpazoid#14]
Hello, I found a repository where melpazoid is used for CI on GitHub Actions, using `melpazoid.yml` from your repository.

It [failed unconditionally on PRs](https://github.com/tecosaur/emacs-everywhere/actions), but I fixed it by setting `LOCAL_REPO` environment variable: https://github.com/tecosaur/emacs-everywhere/pull/17/files

I think either your documentation or `melpazoid.yml` needs an update to ensure that `LOCAL_REPO` is set when used in individual package repositories.

**Comment by riscy** [comment]
Thank you for pointing this out, this looks like it's an oversight on my part.  I'll add that!

**Comment by akirak** [comment]
Thanks for the update. The issue was fixed on develop branch, so I'll close this PR.
