### ISSUE TITLE
Suggest using %F for `%Y-%m-%d`[uppercased y] time string only

### ISSUE THREAD

**Issue by alexluigit** [riscy/melpazoid#18]
680f58ec82d5de7472b288abf7944c42a6c51905 introduced a suggestion for the `%Y-%m-%d` time string. But for some reason it also prints the suggestion for `%y-%m-%d` (with _lower-cased_ y). 

Ref: https://github.com/alexluigit/dirvish/blob/4a99dc5c9a2d3575183cd368284bb217b35f8007/dirvish-widgets.el#L30
Ref: https://github.com/alexluigit/dirvish/actions/runs/3189587662/jobs/5203562609#step:5:19

**Comment by riscy** [comment]
Thanks for reporting this!  I believe I'm mistakenly matching case-insensitively, so I need to set `case-fold-search` to nil.

**Comment by riscy** [comment]
Thanks again -- I think this one has been addressed in https://github.com/riscy/melpazoid/commit/60303dff1d95a47a7b61d3961f1daa9efa999d91, but let me know if not.
