### ISSUE TITLE
file-missing Searching for program: "No such file or directory git"

### ISSUE THREAD

**Issue by f3sch** [riscy/melpazoid#19]
Hi,

I am trying to write my first emacs package. While going through all the bells and whistles and the thought of submitting it later on melpa, I am trying to use this workflow. However, I get the following error on https://github.com/f3sch/b4.el/tree/fix_melpazoid (on master I tried to modify the action): 
![image](https://user-images.githubusercontent.com/42321018/199194362-e6e99ba3-52cd-4952-95bc-e8bd43bc5a0e.png)

Not sure what is going on there...
On master it is failing with the same message and using the action provided by https://github.com/alphapapa/makem.sh works.

Any help is appreciated as I am not really familiar with github actions.
Thanks.

**Comment by riscy** [comment]
Hello - clearly I need to pay more attention to the melpazoid issues.

This *looks* like everything is operating as expected; your package is being loaded in and expects "git" to be available.  Most -- but not all -- systems will already have git installed (melpazoid doesn't have git).

Let me know if this doesn't answer your question!
