### ISSUE TITLE
Check for existing packages by the same name

### ISSUE THREAD

**Issue by tarsius** [riscy/melpazoid#6]
Melpa isn't a complete archive of Emacs packages. I think you should also check the Emacsmirror (including Emacsattic). You could use the [`epkg` package](https://github.com/emacscollective/epkg) for that purpose or you could just get the necessary information from the Emacsmirror's [data repository](https://github.com/emacsmirror/epkgs) directly.

As an example, this would have allowed you to notice when accepting https://github.com/melpa/melpa/pull/6725 that https://www.emacswiki.org/emacs/download/srfi.el also exists. (You won't be able to see that *now* anymore, because I am updating the Emacsmirror to mirror that new implementation. That often is the right thing to do but its still a good idea to inspect the older implementation and to make the author of the new one aware of it in case they want to lift some ideas or something.)

**Comment by riscy** [comment]
This is a great idea and should be fairly easy to implement.  It will surely prevent oversights like with srfi. :)

**Comment by tarsius** [comment]
You're not waiting for me or anything like that?

**Comment by riscy** [comment]
Nope, this is all set.  Thanks a lot for the suggestion. :)
